### PR TITLE
Fix/string to array

### PR DESCRIPTION
**Pull request by trx35479**
- update incaprule unit test
- add update function for incap rules
- add utils to convert string to array
- update incap acl security rule to parameter to use array instead of string comma separated values

### CODE REVIEW

**Comment by trx35479** [comment]
@brramos Please review the changes. More resources will be added to this provider.

**Comment by anandkunal** [comment]
Looks good. We're going to get in a big change to ACL rules + add a resource for WAF rules today. @banderson0421 and I will look at layering this in.

**Comment by trx35479** [comment]
@anandkunal this fix will also add update to incap rules that currently being handled by the same create function. Currently, if we update the incap_rules, it create a new rule instead of updating the existing.

**Comment by anandkunal** [comment]
Understood @trx35479 - can we split the changes from this branch? Would like to get fixes in and reviewed separately. Thanks!

**Comment by anandkunal** [comment]
Closing this out as Incap Rule has moved to APIv2.

**Pull request closed without merging**
