### PR TITLE
SubAccount resource

### PR DESCRIPTION
**Pull request by mazooz-chen**

### CODE REVIEW

**Comment by anandkunal** [comment]
Hi @mazooz-chen - were you able to get in some resource-specific tests?

**Comment by acatte10** [comment]
hello @anandkunal . Do you know when this "subaccount" creation/deletion feature will be available in the terraform provider please ? thanks

**Comment by smehboub** [comment]
Hello @mazooz-chen,

It would be really nice to enjoy your work, thank you for this.
Any news, please ?

Thanks in advance.
Rgs,

Sophian Mehboub

**Comment by mazooz-chen** [comment]
@anandkunal 
Hi, 
Is something missing ? What should i do so this PR will be merged ? 

Thank you

**Comment by acatte10** [comment]
@anandkunal up on this topic :) any idea if it's ready to merge or not please ?

**Comment by anandkunal** [comment]
Hi @acatte10 - we're doing a pretty big refactor of the codebase, some of it should be landing in the next week or so. We'll get to this when we're through the changes. Thanks for your patience.

**Comment by mazooz-chen** [comment]
Hi @anandkunal 
I rebased my PR + solved the conflicts.
Do you have estimation when the PR will be merged ? anything else that you need me to do before merging ?

Thanks

**Comment by pablo-s-martinez** [comment]
@mazooz-chen thanks a lot for your contribution. I'll be adding the missing resource acceptance tests
I've forked your repo branch, working on it now. Fixing in addition some minor fixes, once ready will share a PR to your forked repo and we can cascade to this

Best,
Pablo

**Comment by mazooz-chen** [comment]
@pablo-s-martinez Thanks ! Let me know if I can help with anything

**Pull request merged**
