### PR TITLE
User resource

### PR DESCRIPTION
**Pull request by mazooz-chen**

### CODE REVIEW

**Comment by pablo-s-martinez** [comment]
Hi Chen

Apologies for the late response as i was off few days

Your commits are already merged into master via a forked repo from your branch. You can follow the commits history in master

Thanks!
Pablo

נשלח מה-iPhone שלי

**Comment by pablo-s-martinez** [comment]
I see i mixed between the 2 :-), let me check with the team, i will reply back about user resource

נשלח מה-iPhone שלי

**Comment by mazooz-chen** [comment]
Hi @pablo-s-martinez , i fixed the PR and rebased, if you want to take a look

**Comment by PJHRobles** [comment]
Hi is there a reason why this wasn't merged?

**Comment by BrachaY** [comment]
Hi @PJHRobles 
A new User resource will be released in the near future.

**Comment by PJHRobles** [comment]
> Hi @PJHRobles A new User resource will be released in the near future.

Thank you for the response. Re near future - how soon are we talking about? Are we thinking days, weeks, etc?

**Pull request closed without merging**
